const horseRacingFactsData = [
    {
        "FECHA": "Abril 8",
        "HIPÓDROMO": "Keeneland",
        "EVENTO": "Ashland S.",
        "GRADO": "I",
        "PREMIO": "$600MIL",
        "DISTANCIA": "1 & 1/16 ",
        "EDAD": "3",
        "SEXO": "H",
        "SUPERFICIE": "Arena",
    },
    {
        "FECHA": "Abril 8",
        "HIPÓDROMO": "Aqueduct",
        "EVENTO": "Transylvania S.",
        "GRADO": "III ",
        "PREMIO": "$400MIL",
        "DISTANCIA": "1 & 1/16 ",
        "EDAD": "2",
        "SEXO": "M",
        "SUPERFICIE": "Grama",
    },
    {
        "FECHA": "Abril 8",
        "HIPÓDROMO": "Keeneland",
        "EVENTO": "Blue Grass S. (kd)",
        "GRADO": "II",
        "PREMIO": "$400MIL",
        "DISTANCIA": "1 & 1/16 ",
        "EDAD": "1",
        "SEXO": "M",
        "SUPERFICIE": "Arena",
    },
    {
        "FECHA": "Abril 8",
        "HIPÓDROMO": "Keeneland",
        "EVENTO": "Ashland S.",
        "GRADO": "I",
        "PREMIO": "$600MIL",
        "DISTANCIA": "1 & 1/16 ",
        "EDAD": "3",
        "SEXO": "H",
        "SUPERFICIE": "Arena",
    },
    {
        "FECHA": "Abril 8",
        "HIPÓDROMO": "Aqueduct",
        "EVENTO": "Transylvania S.",
        "GRADO": "III ",
        "PREMIO": "$400MIL",
        "DISTANCIA": "1 & 1/16 ",
        "EDAD": "2",
        "SEXO": "M",
        "SUPERFICIE": "Grama",
    },
    {
        "FECHA": "Abril 8",
        "HIPÓDROMO": "Keeneland",
        "EVENTO": "Blue Grass S. (kd)",
        "GRADO": "II",
        "PREMIO": "$400MIL",
        "DISTANCIA": "1 & 1/16 ",
        "EDAD": "1",
        "SEXO": "M",
        "SUPERFICIE": "Arena",
    },
    {
        "FECHA": "Abril 8",
        "HIPÓDROMO": "Keeneland",
        "EVENTO": "Ashland S.",
        "GRADO": "I",
        "PREMIO": "$600MIL",
        "DISTANCIA": "1 & 1/16 ",
        "EDAD": "3",
        "SEXO": "H",
        "SUPERFICIE": "Arena",
    },
    {
        "FECHA": "Abril 8",
        "HIPÓDROMO": "Aqueduct",
        "EVENTO": "Transylvania S.",
        "GRADO": "III ",
        "PREMIO": "$400MIL",
        "DISTANCIA": "1 & 1/16 ",
        "EDAD": "2",
        "SEXO": "M",
        "SUPERFICIE": "Grama",
    },
    {
        "FECHA": "Abril 8",
        "HIPÓDROMO": "Keeneland",
        "EVENTO": "Blue Grass S. (kd)",
        "GRADO": "II",
        "PREMIO": "$400MIL",
        "DISTANCIA": "1 & 1/16 ",
        "EDAD": "1",
        "SEXO": "M",
        "SUPERFICIE": "Arena",
    }
];
export default horseRacingFactsData; 